global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using ParkNetApp.Data;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using ParkNetApp.Data.Entities;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using System.Security.Claims;
